# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.

theme = "blowfish"
baseURL = "https://n9o.xyz/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 18
summaryLength = 30

buildDrafts = false
buildFuture = false

googleAnalytics = "G-R94R4YKFEC"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 1
  includeNewer = true
  toLower = true

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 10

    [[related.indices]]
        name = "date"
        weight = 0

    [[related.indices]]
      applyFilter = true
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

